name 'checkmka'
source_url       'https://github.com/emo3/checkmka'
issues_url       'https://github.com/emo3/checkmka/issues'
maintainer       'Ed Overton'
maintainer_email 'you1@example.com'
chef_version     '>= 16.0'
license          'Apache-2.0'
description      'Installs/Configures checkmk agent'
version          '1.2.0'

supports 'redhat'
supports 'centos'
supports 'almalinux'

depends 'line'
